package me.pajic.mapstitch.config;

import dev.kikugie.fletching_table.annotation.fabric.Entrypoint;
import me.pajic.mapstitch.MapStitch;
import me.pajic.mapstitch.MapStitchClient;
import me.pajic.mapstitch.minimap.MinimapBackground;
import me.pajic.mapstitch.minimap.MinimapPosition;
import me.pajic.mapstitch.worldmap.TextHighlightColor;
import net.caffeinemc.mods.sodium.api.config.ConfigEntryPoint;
import net.caffeinemc.mods.sodium.api.config.ConfigState;
import net.caffeinemc.mods.sodium.api.config.option.Range;
import net.caffeinemc.mods.sodium.api.config.structure.ConfigBuilder;
import net.minecraft.client.Minecraft;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
//? neoforge {
/*import net.caffeinemc.mods.sodium.api.config.ConfigEntryPointForge;

@ConfigEntryPointForge(MapStitch.MOD_ID)
*///?}
@SuppressWarnings("unused")
@Entrypoint("sodium:config_api_user")
public class ModSodiumConfig implements ConfigEntryPoint {

	private static final Minecraft MC = Minecraft.getInstance();

    @Override
    public void registerConfigLate(ConfigBuilder builder) {
        builder.registerOwnModOptions()
                .setName("MapStitch")
                .setColorTheme(builder.createColorTheme().setBaseThemeRGB(0xb388eb))
                .setNonTintedIcon(Identifier.parse("mapstitch:textures/config_icon.png"))
                .addPage(builder.createOptionPage()
                        .setName(Component.translatable("mapstitch.client_config.minimap"))
						.addOption(builder.createEnumOption(MapStitch.id("minimap_position"), MinimapPosition.class)
								.setName(Component.translatable("mapstitch.client_config.minimap.position"))
								.setTooltip(Component.translatable("mapstitch.client_config.minimap.position.desc"))
								.setDefaultValue(MinimapPosition.TOP_RIGHT)
								.setElementNameProvider(MinimapPosition::getName)
								.setBinding(e -> MapStitchClient.CONFIG.minimap.position.validateAndSet(e), () -> MapStitchClient.CONFIG.minimap.position.get())
								.setStorageHandler(MapStitchClient.CONFIG::save))
						.addOption(builder.createIntegerOption(MapStitch.id("minimap_size"))
								.setName(Component.translatable("mapstitch.client_config.minimap.size"))
								.setTooltip(Component.translatable("mapstitch.client_config.minimap.size.desc"))
								.setDefaultValue(19)
								.setValueFormatter(value -> Component.literal(String.format("%.2fx", 0.05 + (value * 0.05))))
								.setRange(0, 39, 1)
								.setBinding(i -> MapStitchClient.CONFIG.minimap.size.validateAndSet(i), () -> MapStitchClient.CONFIG.minimap.size.get())
								.setStorageHandler(MapStitchClient.CONFIG::save))
						.addOption(builder.createEnumOption(MapStitch.id("minimap_background"), MinimapBackground.class)
								.setName(Component.translatable("mapstitch.client_config.minimap.background"))
								.setTooltip(Component.translatable("mapstitch.client_config.minimap.background.desc"))
								.setDefaultValue(MinimapBackground.CLEAR)
								.setElementNameProvider(MinimapBackground::getName)
								.setBinding(e -> MapStitchClient.CONFIG.minimap.background.validateAndSet(e), () -> MapStitchClient.CONFIG.minimap.background.get())
								.setStorageHandler(MapStitchClient.CONFIG::save))
						.addOption(builder.createIntegerOption(MapStitch.id("minimap_background_opacity"))
								.setName(Component.translatable("mapstitch.client_config.minimap.backgroundOpacity"))
								.setTooltip(Component.translatable("mapstitch.client_config.minimap.backgroundOpacity.desc"))
								.setDefaultValue(50)
								.setRange(0, 100, 1)
								.setValueFormatter(value -> Component.literal(value + "%"))
								.setBinding(i -> MapStitchClient.CONFIG.minimap.backgroundOpacity.validateAndSet(i), () -> MapStitchClient.CONFIG.minimap.backgroundOpacity.get())
								.setEnabledProvider(state -> state.readEnumOption(MapStitch.id("minimap_background"), MinimapBackground.class) == MinimapBackground.CLEAR, MapStitch.id("minimap_background"))
								.setStorageHandler(MapStitchClient.CONFIG::save))
						.addOption(builder.createBooleanOption(MapStitch.id("prevent_effect_overlap"))
								.setName(Component.translatable("mapstitch.client_config.minimap.preventEffectOverlap"))
								.setTooltip(Component.translatable("mapstitch.client_config.minimap.preventEffectOverlap.desc"))
								.setDefaultValue(true)
								.setBinding(bl -> MapStitchClient.CONFIG.minimap.preventEffectOverlap.validateAndSet(bl), () -> MapStitchClient.CONFIG.minimap.preventEffectOverlap.get())
								.setStorageHandler(MapStitchClient.CONFIG::save))
						.addOption(builder.createIntegerOption(MapStitch.id("minimap_x_offset"))
								.setName(Component.translatable("mapstitch.client_config.minimap.xOffset"))
								.setTooltip(Component.translatable("mapstitch.client_config.minimap.xOffset.desc"))
								.setDefaultValue(0)
								.setValueFormatter(value -> Component.literal(String.valueOf(value)))
								.setRangeProvider(cs -> new Range(-MC.getWindow().getGuiScaledWidth(), MC.getWindow().getGuiScaledWidth(), 1), ConfigState.UPDATE_ON_REBUILD)
								.setBinding(i -> MapStitchClient.CONFIG.minimap.xOffset.validateAndSet(i), () -> MapStitchClient.CONFIG.minimap.xOffset.get())
								.setStorageHandler(MapStitchClient.CONFIG::save))
						.addOption(builder.createIntegerOption(MapStitch.id("minimap_y_offset"))
								.setName(Component.translatable("mapstitch.client_config.minimap.yOffset"))
								.setTooltip(Component.translatable("mapstitch.client_config.minimap.yOffset.desc"))
								.setDefaultValue(0)
								.setValueFormatter(value -> Component.literal(String.valueOf(value)))
								.setRangeProvider(cs -> new Range(-MC.getWindow().getGuiScaledHeight(), MC.getWindow().getGuiScaledHeight(), 1), ConfigState.UPDATE_ON_REBUILD)
								.setBinding(i -> MapStitchClient.CONFIG.minimap.yOffset.validateAndSet(i), () -> MapStitchClient.CONFIG.minimap.yOffset.get())
								.setStorageHandler(MapStitchClient.CONFIG::save)))
				.addPage(builder.createOptionPage()
						.setName(Component.translatable("mapstitch.client_config.worldMap"))
						.addOption(builder.createEnumOption(MapStitch.id("worldmap_text_highlight_color"), TextHighlightColor.class)
								.setName(Component.translatable("mapstitch.client_config.worldMap.textHighlightColor"))
								.setTooltip(Component.translatable("mapstitch.client_config.worldMap.textHighlightColor.desc"))
								.setDefaultValue(TextHighlightColor.YELLOW)
								.setElementNameProvider(TextHighlightColor::getName)
								.setBinding(e -> MapStitchClient.CONFIG.worldMap.textHighlightColor.validateAndSet(e), () -> MapStitchClient.CONFIG.worldMap.textHighlightColor.get())
								.setStorageHandler(MapStitchClient.CONFIG::save))
						.addOption(builder.createIntegerOption(MapStitch.id("worldmap_text_background_opacity"))
								.setName(Component.translatable("mapstitch.client_config.worldMap.textBackgroundOpacity"))
								.setTooltip(Component.translatable("mapstitch.client_config.worldMap.textBackgroundOpacity.desc"))
								.setDefaultValue(50)
								.setRange(0, 100, 1)
								.setValueFormatter(value -> Component.literal(value + "%"))
								.setBinding(i -> MapStitchClient.CONFIG.worldMap.textBackgroundOpacity.validateAndSet(i), () -> MapStitchClient.CONFIG.worldMap.textBackgroundOpacity.get())
								.setStorageHandler(MapStitchClient.CONFIG::save))
						.addOption(builder.createBooleanOption(MapStitch.id("show_buttons"))
								.setName(Component.translatable("mapstitch.client_config.worldMap.buttons"))
								.setTooltip(Component.translatable("mapstitch.client_config.worldMap.buttons.desc"))
								.setDefaultValue(true)
								.setBinding(bl -> MapStitchClient.CONFIG.worldMap.buttons.validateAndSet(bl), () -> MapStitchClient.CONFIG.worldMap.buttons.get())
								.setStorageHandler(MapStitchClient.CONFIG::save))
						.addOption(builder.createBooleanOption(MapStitch.id("show_help"))
								.setName(Component.translatable("mapstitch.client_config.worldMap.help"))
								.setTooltip(Component.translatable("mapstitch.client_config.worldMap.help.desc"))
								.setDefaultValue(true)
								.setBinding(bl -> MapStitchClient.CONFIG.worldMap.help.validateAndSet(bl), () -> MapStitchClient.CONFIG.worldMap.help.get())
								.setStorageHandler(MapStitchClient.CONFIG::save)))
                .addPage(builder.createOptionPage()
                        .setName(Component.translatable("mapstitch.client_config.minimapInfo"))
                        .addOption(builder.createBooleanOption(MapStitch.id("real_time"))
                                .setName(Component.translatable("mapstitch.client_config.minimapInfo.realTime"))
                                .setTooltip(Component.translatable("mapstitch.client_config.minimapInfo.realTime"))
                                .setDefaultValue(false)
                                .setBinding(bl -> MapStitchClient.CONFIG.minimapInfo.realTime.validateAndSet(bl), () -> MapStitchClient.CONFIG.minimapInfo.realTime.get())
                                .setStorageHandler(MapStitchClient.CONFIG::save))
                        .addOption(builder.createEnumOption(MapStitch.id("real_time_format"), RealTimeFormat.class)
                                .setName(Component.translatable("mapstitch.client_config.minimapInfo.realTimeFormat"))
                                .setTooltip(Component.translatable("mapstitch.client_config.minimapInfo.realTimeFormat"))
                                .setDefaultValue(RealTimeFormat.H24)
                                .setElementNameProvider(RealTimeFormat::getName)
                                .setBinding(e -> MapStitchClient.CONFIG.minimapInfo.realTimeFormat.validateAndSet(e), () -> MapStitchClient.CONFIG.minimapInfo.realTimeFormat.get())
                                .setStorageHandler(MapStitchClient.CONFIG::save))
                        .addOption(builder.createBooleanOption(MapStitch.id("game_time"))
                                .setName(Component.translatable("mapstitch.client_config.minimapInfo.gameTime"))
                                .setTooltip(Component.translatable("mapstitch.client_config.minimapInfo.gameTime"))
                                .setDefaultValue(false)
                                .setBinding(bl -> MapStitchClient.CONFIG.minimapInfo.gameTime.validateAndSet(bl), () -> MapStitchClient.CONFIG.minimapInfo.gameTime.get())
                                .setStorageHandler(MapStitchClient.CONFIG::save))
                        .addOption(builder.createBooleanOption(MapStitch.id("coordinates"))
                                .setName(Component.translatable("mapstitch.client_config.minimapInfo.coordinates"))
                                .setTooltip(Component.translatable("mapstitch.client_config.minimapInfo.coordinates"))
                                .setDefaultValue(false)
                                .setBinding(bl -> MapStitchClient.CONFIG.minimapInfo.coordinates.validateAndSet(bl), () -> MapStitchClient.CONFIG.minimapInfo.coordinates.get())
                                .setStorageHandler(MapStitchClient.CONFIG::save))
                        .addOption(builder.createBooleanOption(MapStitch.id("biome"))
                                .setName(Component.translatable("mapstitch.client_config.minimapInfo.biome"))
                                .setTooltip(Component.translatable("mapstitch.client_config.minimapInfo.biome"))
                                .setDefaultValue(false)
                                .setBinding(bl -> MapStitchClient.CONFIG.minimapInfo.biome.validateAndSet(bl), () -> MapStitchClient.CONFIG.minimapInfo.biome.get())
                                .setStorageHandler(MapStitchClient.CONFIG::save))
                        .addOption(builder.createBooleanOption(MapStitch.id("weather"))
                                .setName(Component.translatable("mapstitch.client_config.minimapInfo.weather"))
                                .setTooltip(Component.translatable("mapstitch.client_config.minimapInfo.weather"))
                                .setDefaultValue(false)
                                .setBinding(bl -> MapStitchClient.CONFIG.minimapInfo.weather.validateAndSet(bl), () -> MapStitchClient.CONFIG.minimapInfo.weather.get())
                                .setStorageHandler(MapStitchClient.CONFIG::save))
                );
    }
}
