org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=mapstitch
mod.name=MapStitch
mod.group=me.pajic
mod.version=1.0.10
mod.channel_tag=
mod.authors=pajic
mod.contributors=Luth, MerryDreambound
mod.license=MIT
mod.description=World map and minimap using vanilla maps
mod.sources_url=https://github.com/pajicadvance/mapstitch
mod.homepage_url=https://modrinth.com/mod/mapstitch
mod.issues_url=https://github.com/pajicadvance/mapstitch/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fzzy_config=[VERSIONED]
deps.mixson=[VERSIONED]
deps.sodium=[VERSIONED]

publish.modrinth=etdHQJ0B
publish.curseforge=1595069
publish.github=false
