# general
mod.id = "mapstitch"
mod.name = "MapStitch"
mod.group = "me.pajic"
mod.version = "1.1.1"
mod.description = "World map and minimap using vanilla maps"
mod.authors = "pajic"
mod.contributors = "Luth, MerryDreambound"
mod.license = "MIT"

# links
mod.sources_url = "https://github.com/pajicadvance/mapstitch"
mod.homepage_url = "https://modrinth.com/mod/mapstitch"
mod.issues_url = "https://github.com/pajicadvance/mapstitch/issues"
mod.discord_url = "https://discord.gg/5RkzS66zWb"

# publishing
publish.modrinth = "etdHQJ0B"
publish.curseforge = "1595069"
publish.env.mr = "CLIENT_AND_SERVER" #https://modmuss50.github.io/mod-publish-plugin/platforms/modrinth/#all-options
publish.env.cf.client = true
publish.env.cf.server = true
publish.dry_run = false

# loom
loomx.loom_version = "1.17-SNAPSHOT"

# dependencies
loader.fabric = "0.19.3"
dep.mixinconstraints.coords = "com.moulberry:$id:$version"
dep.fzzy_config.coords = "me.fzzyhmstrs:$id:$version"
dep.fzzy_config.slug = "fzzy-config"
dep.sodium.coords = "net.caffeinemc:$id-$loader-api:$version"
dep.sodium_runtime.coords = "net.caffeinemc:sodium-$loader:$version"
dep.trinkets.coords = "eu.pb4:$id:$version"
dep.ohmega.coords = "maven.modrinth:$id:$version-$loader,$mc"
dep.curios.coords = "top.theillusivec4.$id:$id-$loader:$version"
dep.emi.coords = "dev.emi:$id-$loader:$version"
dep.remapped.coords = "maven.modrinth:$id:$version"
include.mixinconstraints = "1.1.0"

[fabric]
dep.fabric-api.coords = "net.fabricmc.fabric-api:$id:$version"
dep.modmenu.coords = "com.terraformersmc:$id:$version"
dep.ohmega.range = ">=1.5.21 <1.6"
dev.runtime_optionals = ["modmenu", "trinkets"]

[neoforge]
dep.ohmega.range = "[1.5.21, 1.6)"
dev.runtime_optionals = ["curios", "emi"]


["1.21.1"]
mod.mc_releases = ["1.21", "1.21.1"]
loader.neo = "21.1.244"
dep.trinkets.coords = "dev.emi:$id:$version"
optional.sodium = "0.8.12+mc1.21.1"
runtime.sodium_runtime = "0.8.12+mc1.21.1"
optional.ohmega = "1.5.21"
optional.emi = "1.1.24+1.21.1"

[fabric."1.21.1"]
mod.mc_compat = ">=1.21 <=1.21.1"
required.fabric-api = "0.116.14+1.21.1"
required.fzzy_config = "0.7.6+1.21"
optional.modmenu = "11.0.4"
optional.trinkets = "3.10.0"

[neoforge."1.21.1"]
mod.mc_compat = "[1.21, 1.21.1]"
required.fzzy_config = "0.7.6+1.21+neoforge"
optional.curios = "9.5.1+1.21.1"


["26.1.2"]
mod.mc_releases = ["26.1", "26.1.1", "26.1.2"]
loader.neo = "26.1.2.87"
optional.sodium = "0.9.1+mc26.1.2"
runtime.sodium_runtime = "0.9.1+mc26.1.2"
optional.trinkets = "4.0.0-beta.3+26.1"
optional.ohmega = "1.5.21"

[fabric."26.1.2"]
mod.mc_compat = "~26.1"
required.fabric-api = "0.155.2+26.1.2"
required.fzzy_config = "0.7.6+26.1-pre-3"
optional.modmenu = "18.0.0"
optional.remapped = "bBfNuGXN"

[neoforge."26.1.2"]
mod.mc_compat = "[26.1, 26.2)"
required.fzzy_config = "0.7.6+26.1-pre-3+neoforge"
optional.curios = "15.0.0+26.1.2"


["26.2"]
mod.mc_releases = ["26.2"]
loader.neo = "26.2.0.59"
optional.sodium = "0.9.1+mc26.2"
runtime.sodium_runtime = "0.9.1+mc26.2"
optional.trinkets = "4.1.0-beta.2+26.2"
optional.ohmega = "1.5.21"

[fabric."26.2"]
mod.mc_compat = "~26.2"
required.fabric-api = "0.155.2+26.2"
required.fzzy_config = "0.7.6+26.2-pre-3"
optional.modmenu = "20.0.1"
optional.remapped = "2.0.2"

[neoforge."26.2"]
mod.mc_compat = "[26.2, 26.3)"
required.fzzy_config = "0.7.6+26.2+neoforge"
optional.curios = "16.0.0+26.2"
